"""baseline schema

Revision ID: e36d1ddb4783
Revises:
Create Date: 2026-06-02 21:53:46.769730

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e36d1ddb4783"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_file_id", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("promptpay_id", sa.String(length=20), nullable=True),
        sa.Column("promptpay_name", sa.String(length=200), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(op.f("ix_brands_is_active"), "brands", ["is_active"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("default", sa.Boolean(), nullable=True),
        sa.Column("permissions", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_default"), "roles", ["default"], unique=False)
    op.create_table(
        "bot_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("bot_token", sa.String(length=100), nullable=False),
        sa.Column("bot_username", sa.String(length=64), nullable=True),
        sa.Column("bot_display_name", sa.String(length=128), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("webhook_url", sa.String(length=500), nullable=True),
        sa.Column("webhook_secret", sa.String(length=128), nullable=True),
        sa.Column("payments_enabled", sa.JSON(), nullable=True),
        sa.Column("default_language", sa.String(length=5), nullable=True),
        sa.Column("default_currency", sa.String(length=5), nullable=True),
        sa.Column("welcome_message", sa.Text(), nullable=True),
        sa.Column("menu_style", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_token"),
        sa.UniqueConstraint("brand_id"),
    )
    op.create_index(op.f("ix_bot_configs_is_active"), "bot_configs", ["is_active"], unique=False)
    op.create_table(
        "bot_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("setting_key", sa.String(length=100), nullable=False),
        sa.Column("setting_value", sa.Text(), nullable=True),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("setting_key", "brand_id", name="uq_setting_key_brand"),
    )
    op.create_index(op.f("ix_bot_settings_brand_id"), "bot_settings", ["brand_id"], unique=False)
    op.create_index(op.f("ix_bot_settings_setting_key"), "bot_settings", ["setting_key"], unique=False)
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_file_id", sa.String(length=255), nullable=True),
        sa.Column("available_from", sa.String(length=5), nullable=True),
        sa.Column("available_until", sa.String(length=5), nullable=True),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_categories_brand_id"), "categories", ["brand_id"], unique=False)
    op.create_table(
        "stores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("kitchen_group_id", sa.BigInteger(), nullable=True),
        sa.Column("rider_group_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("brand_id", "name", name="uq_store_brand_name"),
    )
    op.create_index(op.f("ix_stores_brand_id"), "stores", ["brand_id"], unique=False)
    op.create_index(op.f("ix_stores_is_active"), "stores", ["is_active"], unique=False)
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("referral_id", sa.BigInteger(), nullable=True),
        sa.Column("locale", sa.String(length=5), nullable=True),
        sa.Column(
            "registration_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("banned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("banned_by", sa.BigInteger(), nullable=True),
        sa.Column("ban_reason", sa.Text(), nullable=True),
        sa.Column("privacy_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["banned_by"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["referral_id"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_index(op.f("ix_users_is_banned"), "users", ["is_banned"], unique=False)
    op.create_index(op.f("ix_users_referral_id"), "users", ["referral_id"], unique=False)
    op.create_index(op.f("ix_users_role_id"), "users", ["role_id"], unique=False)
    op.create_table(
        "bought_goods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("buyer_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "bought_datetime", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("unique_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["buyer_id"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("unique_id"),
    )
    op.create_index(op.f("ix_bought_goods_buyer_id"), "bought_goods", ["buyer_id"], unique=False)
    op.create_index(op.f("ix_bought_goods_item_name"), "bought_goods", ["item_name"], unique=False)
    op.create_table(
        "brand_staff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("brand_id", "user_id", "store_id", name="uq_brand_user_store"),
    )
    op.create_index(op.f("ix_brand_staff_brand_id"), "brand_staff", ["brand_id"], unique=False)
    op.create_index("ix_brand_staff_brand_role", "brand_staff", ["brand_id", "role"], unique=False)
    op.create_index(op.f("ix_brand_staff_user_id"), "brand_staff", ["user_id"], unique=False)
    op.create_table(
        "coupons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("discount_type", sa.String(length=10), nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("min_order", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("max_discount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("current_uses", sa.Integer(), nullable=False),
        sa.Column("max_uses_per_user", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_coupons_active_valid", "coupons", ["is_active", "valid_until"], unique=False)
    op.create_index(op.f("ix_coupons_code"), "coupons", ["code"], unique=True)
    op.create_index(op.f("ix_coupons_is_active"), "coupons", ["is_active"], unique=False)
    op.create_table(
        "customer_info",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("phone_number", sa.String(length=50), nullable=True),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column("delivery_note", sa.Text(), nullable=True),
        sa.Column("total_spendings", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("completed_orders_count", sa.Integer(), nullable=False),
        sa.Column("bonus_balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("address_structured", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["telegram_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table(
        "goods",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category_name", sa.String(length=100), nullable=False),
        sa.Column("item_type", sa.String(length=20), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("reserved_quantity", sa.Integer(), nullable=False),
        sa.Column("modifiers", sa.JSON(), nullable=True),
        sa.Column("image_file_id", sa.String(length=255), nullable=True),
        sa.Column("media", sa.JSON(), nullable=True),
        sa.Column("prep_time_minutes", sa.Integer(), nullable=True),
        sa.Column("allergens", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sold_out_today", sa.Boolean(), nullable=False),
        sa.Column("daily_limit", sa.Integer(), nullable=True),
        sa.Column("daily_sold_count", sa.Integer(), nullable=False),
        sa.Column("available_from", sa.String(length=5), nullable=True),
        sa.Column("available_until", sa.String(length=5), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_name"], ["categories.name"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(op.f("ix_goods_brand_id"), "goods", ["brand_id"], unique=False)
    op.create_index(op.f("ix_goods_category_name"), "goods", ["category_name"], unique=False)
    op.create_index(op.f("ix_goods_is_active"), "goods", ["is_active"], unique=False)
    op.create_index(op.f("ix_goods_item_type"), "goods", ["item_type"], unique=False)
    op.create_table(
        "operations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("operation_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "operation_time", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_operations_user_id"), "operations", ["user_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_code", sa.String(length=6), nullable=True),
        sa.Column("buyer_id", sa.BigInteger(), nullable=True),
        sa.Column("total_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("bonus_applied", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=False),
        sa.Column("delivery_address", sa.Text(), nullable=False),
        sa.Column("phone_number", sa.String(length=50), nullable=False),
        sa.Column("delivery_note", sa.Text(), nullable=True),
        sa.Column("bitcoin_address", sa.String(length=100), nullable=True),
        sa.Column("crypto_address", sa.String(length=200), nullable=True),
        sa.Column("payment_coin", sa.String(length=10), nullable=True),
        sa.Column("order_status", sa.String(length=20), nullable=False),
        sa.Column("reserved_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("google_maps_link", sa.String(length=255), nullable=True),
        sa.Column("address_structured", sa.JSON(), nullable=True),
        sa.Column("kitchen_group_message_id", sa.Integer(), nullable=True),
        sa.Column("rider_group_message_id", sa.Integer(), nullable=True),
        sa.Column("estimated_ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_prep_time_minutes", sa.Integer(), nullable=True),
        sa.Column("delivery_zone", sa.String(length=50), nullable=True),
        sa.Column("delivery_fee", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("preferred_time_slot", sa.String(length=50), nullable=True),
        sa.Column("driver_live_location_message_id", sa.Integer(), nullable=True),
        sa.Column("driver_id", sa.BigInteger(), nullable=True),
        sa.Column("customer_live_location_message_id", sa.Integer(), nullable=True),
        sa.Column("chat_opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chat_closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chat_post_delivery_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_receipt_photo", sa.String(length=255), nullable=True),
        sa.Column("payment_verified_by", sa.BigInteger(), nullable=True),
        sa.Column("payment_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("slip_verify_status", sa.String(length=30), nullable=True),
        sa.Column("slip_verify_bank", sa.String(length=20), nullable=True),
        sa.Column("slip_transaction_id", sa.String(length=100), nullable=True),
        sa.Column("slip_verified_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("slip_sender_name", sa.String(length=255), nullable=True),
        sa.Column("slip_receiver_name", sa.String(length=255), nullable=True),
        sa.Column("slip_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_type", sa.String(length=20), nullable=False),
        sa.Column("drop_instructions", sa.Text(), nullable=True),
        sa.Column("drop_location_photo", sa.String(length=255), nullable=True),
        sa.Column("drop_latitude", sa.Float(), nullable=True),
        sa.Column("drop_longitude", sa.Float(), nullable=True),
        sa.Column("drop_media", sa.JSON(), nullable=True),
        sa.Column("delivery_photo", sa.String(length=255), nullable=True),
        sa.Column("delivery_photo_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_photo_by", sa.BigInteger(), nullable=True),
        sa.Column("coupon_code", sa.String(length=32), nullable=True),
        sa.Column("coupon_discount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.CheckConstraint("delivery_type IN ('door', 'dead_drop', 'pickup')", name="ck_orders_delivery_type"),
        sa.CheckConstraint(
            "order_status IN ('pending', 'reserved', 'confirmed', 'preparing', 'ready', 'out_for_delivery', 'delivered', 'cancelled', 'expired')",
            name="ck_orders_order_status",
        ),
        sa.CheckConstraint(
            "payment_method IN ('bitcoin', 'litecoin', 'solana', 'usdt_sol', 'cash', 'promptpay')",
            name="ck_orders_payment_method",
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["buyer_id"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_code"),
    )
    op.create_index(op.f("ix_orders_brand_id"), "orders", ["brand_id"], unique=False)
    op.create_index(op.f("ix_orders_buyer_id"), "orders", ["buyer_id"], unique=False)
    op.create_index("ix_orders_buyer_status", "orders", ["buyer_id", "order_status"], unique=False)
    op.create_index("ix_orders_created_at", "orders", ["created_at"], unique=False)
    op.create_index("ix_orders_order_code", "orders", ["order_code"], unique=False)
    op.create_index("ix_orders_reserved_until", "orders", ["reserved_until"], unique=False)
    op.create_table(
        "reference_codes",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("current_uses", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin_code", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index("ix_reference_codes_active_expires", "reference_codes", ["is_active", "expires_at"], unique=False)
    op.create_index(op.f("ix_reference_codes_created_by"), "reference_codes", ["created_by"], unique=False)
    op.create_index(op.f("ix_reference_codes_is_active"), "reference_codes", ["is_active"], unique=False)
    op.create_table(
        "referral_earnings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("referrer_id", sa.BigInteger(), nullable=False),
        sa.Column("referral_id", sa.BigInteger(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("original_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["referral_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referrer_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_referral_earnings_referral_created", "referral_earnings", ["referral_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_referral_earnings_referrer_created", "referral_earnings", ["referrer_id", "created_at"], unique=False
    )
    op.create_table(
        "saved_carts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("brand_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("items_json", sa.JSON(), nullable=False),
        sa.Column("original_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "saved_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_carts_user_id"), "saved_carts", ["user_id"], unique=False)
    op.create_table(
        "bitcoin_addresses",
        sa.Column("address", sa.String(length=100), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_by", sa.BigInteger(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["used_by"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_index(op.f("ix_bitcoin_addresses_is_used"), "bitcoin_addresses", ["is_used"], unique=False)
    op.create_table(
        "branch_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(length=100), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("reserved_quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["item_name"], ["goods.name"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "item_name", name="uq_branch_inventory_store_item"),
    )
    op.create_index("ix_branch_inventory_item", "branch_inventory", ["item_name"], unique=False)
    op.create_index(op.f("ix_branch_inventory_store_id"), "branch_inventory", ["store_id"], unique=False)
    op.create_table(
        "coupon_usages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coupon_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("discount_applied", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["coupon_id"], ["coupons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_coupon_usages_coupon_id"), "coupon_usages", ["coupon_id"], unique=False)
    op.create_index("ix_coupon_usages_user_coupon", "coupon_usages", ["user_id", "coupon_id"], unique=False)
    op.create_index(op.f("ix_coupon_usages_user_id"), "coupon_usages", ["user_id"], unique=False)
    op.create_table(
        "crypto_addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coin", sa.String(length=10), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_by", sa.BigInteger(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["used_by"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("coin", "address", name="uq_coin_address"),
    )
    op.create_index(op.f("ix_crypto_addresses_coin"), "crypto_addresses", ["coin"], unique=False)
    op.create_index(op.f("ix_crypto_addresses_is_used"), "crypto_addresses", ["is_used"], unique=False)
    op.create_index("ix_crypto_coin_unused", "crypto_addresses", ["coin", "is_used"], unique=False)
    op.create_table(
        "crypto_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("coin", sa.String(length=10), nullable=False),
        sa.Column("receive_address", sa.String(length=200), nullable=False),
        sa.Column("expected_amount", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("expected_amount_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("tx_hash", sa.String(length=200), nullable=True),
        sa.Column("received_amount", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("confirmations", sa.Integer(), nullable=False),
        sa.Column("required_confirmations", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('awaiting', 'detected', 'confirmed', 'expired')", name="ck_crypto_payments_status"
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "delivery_chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.BigInteger(), nullable=False),
        sa.Column("sender_role", sa.String(length=20), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=True),
        sa.Column("photo_file_id", sa.String(length=255), nullable=True),
        sa.Column("location_lat", sa.Float(), nullable=True),
        sa.Column("location_lng", sa.Float(), nullable=True),
        sa.Column("is_live_location", sa.Boolean(), nullable=False),
        sa.Column("live_location_update_count", sa.Integer(), nullable=True),
        sa.Column("telegram_message_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_delivery_chat_order_created", "delivery_chat_messages", ["order_id", "created_at"], unique=False
    )
    op.create_table(
        "inventory_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(length=100), nullable=True),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column("quantity_change", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("admin_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["admin_id"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["item_name"], ["goods.name"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_inventory_log_item_timestamp", "inventory_log", ["item_name", "timestamp"], unique=False)
    op.create_index(op.f("ix_inventory_log_order_id"), "inventory_log", ["order_id"], unique=False)
    op.create_index(op.f("ix_inventory_log_timestamp"), "inventory_log", ["timestamp"], unique=False)
    op.create_index("ix_inventory_log_type_timestamp", "inventory_log", ["change_type", "timestamp"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("item_name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("selected_modifiers", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"], unique=False)
    op.create_table(
        "reference_code_usages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("used_by", sa.BigInteger(), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["code"], ["reference_codes.code"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["used_by"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "used_by", name="uq_code_user"),
    )
    op.create_index(op.f("ix_reference_code_usages_code"), "reference_code_usages", ["code"], unique=False)
    op.create_index("ix_reference_code_usages_used_at", "reference_code_usages", ["used_at"], unique=False)
    op.create_index(op.f("ix_reference_code_usages_used_by"), "reference_code_usages", ["used_by"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("item_name", sa.String(length=100), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["item_name"], ["goods.name"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "user_id", name="uq_review_order_user"),
    )
    op.create_index("ix_reviews_item_rating", "reviews", ["item_name", "rating"], unique=False)
    op.create_index(op.f("ix_reviews_order_id"), "reviews", ["order_id"], unique=False)
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    op.create_table(
        "shopping_cart",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("item_name", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("selected_modifiers", sa.JSON(), nullable=True),
        sa.Column("brand_id", sa.Integer(), nullable=True),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["item_name"], ["goods.name"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "item_name", "brand_id", name="uq_cart_user_item_brand"),
    )
    op.create_index(op.f("ix_shopping_cart_brand_id"), "shopping_cart", ["brand_id"], unique=False)
    op.create_index(op.f("ix_shopping_cart_expires_at"), "shopping_cart", ["expires_at"], unique=False)
    op.create_index(op.f("ix_shopping_cart_store_id"), "shopping_cart", ["store_id"], unique=False)
    op.create_index("ix_shopping_cart_user_added", "shopping_cart", ["user_id", "added_at"], unique=False)
    op.create_index("ix_shopping_cart_user_brand", "shopping_cart", ["user_id", "brand_id"], unique=False)
    op.create_table(
        "support_tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_code", sa.String(length=8), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("assigned_to", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assigned_to"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_support_tickets_status", "support_tickets", ["status"], unique=False)
    op.create_index(op.f("ix_support_tickets_ticket_code"), "support_tickets", ["ticket_code"], unique=True)
    op.create_index(op.f("ix_support_tickets_user_id"), "support_tickets", ["user_id"], unique=False)
    op.create_index("ix_support_tickets_user_status", "support_tickets", ["user_id", "status"], unique=False)
    op.create_table(
        "ticket_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.BigInteger(), nullable=False),
        sa.Column("sender_role", sa.String(length=10), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["support_tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ticket_messages_ticket_id"), "ticket_messages", ["ticket_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_messages_ticket_id"), table_name="ticket_messages")
    op.drop_table("ticket_messages")
    op.drop_index("ix_support_tickets_user_status", table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_user_id"), table_name="support_tickets")
    op.drop_index(op.f("ix_support_tickets_ticket_code"), table_name="support_tickets")
    op.drop_index("ix_support_tickets_status", table_name="support_tickets")
    op.drop_table("support_tickets")
    op.drop_index("ix_shopping_cart_user_brand", table_name="shopping_cart")
    op.drop_index("ix_shopping_cart_user_added", table_name="shopping_cart")
    op.drop_index(op.f("ix_shopping_cart_store_id"), table_name="shopping_cart")
    op.drop_index(op.f("ix_shopping_cart_expires_at"), table_name="shopping_cart")
    op.drop_index(op.f("ix_shopping_cart_brand_id"), table_name="shopping_cart")
    op.drop_table("shopping_cart")
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_order_id"), table_name="reviews")
    op.drop_index("ix_reviews_item_rating", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_reference_code_usages_used_by"), table_name="reference_code_usages")
    op.drop_index("ix_reference_code_usages_used_at", table_name="reference_code_usages")
    op.drop_index(op.f("ix_reference_code_usages_code"), table_name="reference_code_usages")
    op.drop_table("reference_code_usages")
    op.drop_index("ix_order_items_order_id", table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_inventory_log_type_timestamp", table_name="inventory_log")
    op.drop_index(op.f("ix_inventory_log_timestamp"), table_name="inventory_log")
    op.drop_index(op.f("ix_inventory_log_order_id"), table_name="inventory_log")
    op.drop_index("ix_inventory_log_item_timestamp", table_name="inventory_log")
    op.drop_table("inventory_log")
    op.drop_index("ix_delivery_chat_order_created", table_name="delivery_chat_messages")
    op.drop_table("delivery_chat_messages")
    op.drop_table("crypto_payments")
    op.drop_index("ix_crypto_coin_unused", table_name="crypto_addresses")
    op.drop_index(op.f("ix_crypto_addresses_is_used"), table_name="crypto_addresses")
    op.drop_index(op.f("ix_crypto_addresses_coin"), table_name="crypto_addresses")
    op.drop_table("crypto_addresses")
    op.drop_index(op.f("ix_coupon_usages_user_id"), table_name="coupon_usages")
    op.drop_index("ix_coupon_usages_user_coupon", table_name="coupon_usages")
    op.drop_index(op.f("ix_coupon_usages_coupon_id"), table_name="coupon_usages")
    op.drop_table("coupon_usages")
    op.drop_index(op.f("ix_branch_inventory_store_id"), table_name="branch_inventory")
    op.drop_index("ix_branch_inventory_item", table_name="branch_inventory")
    op.drop_table("branch_inventory")
    op.drop_index(op.f("ix_bitcoin_addresses_is_used"), table_name="bitcoin_addresses")
    op.drop_table("bitcoin_addresses")
    op.drop_index(op.f("ix_saved_carts_user_id"), table_name="saved_carts")
    op.drop_table("saved_carts")
    op.drop_index("ix_referral_earnings_referrer_created", table_name="referral_earnings")
    op.drop_index("ix_referral_earnings_referral_created", table_name="referral_earnings")
    op.drop_table("referral_earnings")
    op.drop_index(op.f("ix_reference_codes_is_active"), table_name="reference_codes")
    op.drop_index(op.f("ix_reference_codes_created_by"), table_name="reference_codes")
    op.drop_index("ix_reference_codes_active_expires", table_name="reference_codes")
    op.drop_table("reference_codes")
    op.drop_index("ix_orders_reserved_until", table_name="orders")
    op.drop_index("ix_orders_order_code", table_name="orders")
    op.drop_index("ix_orders_created_at", table_name="orders")
    op.drop_index("ix_orders_buyer_status", table_name="orders")
    op.drop_index(op.f("ix_orders_buyer_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_brand_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_operations_user_id"), table_name="operations")
    op.drop_table("operations")
    op.drop_index(op.f("ix_goods_item_type"), table_name="goods")
    op.drop_index(op.f("ix_goods_is_active"), table_name="goods")
    op.drop_index(op.f("ix_goods_category_name"), table_name="goods")
    op.drop_index(op.f("ix_goods_brand_id"), table_name="goods")
    op.drop_table("goods")
    op.drop_table("customer_info")
    op.drop_index(op.f("ix_coupons_is_active"), table_name="coupons")
    op.drop_index(op.f("ix_coupons_code"), table_name="coupons")
    op.drop_index("ix_coupons_active_valid", table_name="coupons")
    op.drop_table("coupons")
    op.drop_index(op.f("ix_brand_staff_user_id"), table_name="brand_staff")
    op.drop_index("ix_brand_staff_brand_role", table_name="brand_staff")
    op.drop_index(op.f("ix_brand_staff_brand_id"), table_name="brand_staff")
    op.drop_table("brand_staff")
    op.drop_index(op.f("ix_bought_goods_item_name"), table_name="bought_goods")
    op.drop_index(op.f("ix_bought_goods_buyer_id"), table_name="bought_goods")
    op.drop_table("bought_goods")
    op.drop_index(op.f("ix_users_role_id"), table_name="users")
    op.drop_index(op.f("ix_users_referral_id"), table_name="users")
    op.drop_index(op.f("ix_users_is_banned"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_stores_is_active"), table_name="stores")
    op.drop_index(op.f("ix_stores_brand_id"), table_name="stores")
    op.drop_table("stores")
    op.drop_index(op.f("ix_categories_brand_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_bot_settings_setting_key"), table_name="bot_settings")
    op.drop_index(op.f("ix_bot_settings_brand_id"), table_name="bot_settings")
    op.drop_table("bot_settings")
    op.drop_index(op.f("ix_bot_configs_is_active"), table_name="bot_configs")
    op.drop_table("bot_configs")
    op.drop_index(op.f("ix_roles_default"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_brands_is_active"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###
